version: '3.8'

services:
  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: frontier-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
      - ./config/ollama:/config
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_FLASH_ATTENTION=true
    # Note: deploy.resources is only supported in Docker Swarm mode
    # For standard docker-compose, resource limits should be set in Docker Desktop
    # or via docker run flags. Uncomment below if using Docker Swarm:
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${OLLAMA_MEMORY_LIMIT:-64G}
    #     reservations:
    #       memory: ${OLLAMA_MEMORY_RESERVATION:-32G}
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    mem_limit: ${OLLAMA_MEMORY_LIMIT:-64g}
    memswap_limit: ${OLLAMA_MEMORY_LIMIT:-64g}
    mem_reservation: ${OLLAMA_MEMORY_RESERVATION:-32g}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontier-llm-network

  # Aider development environment (optional)
  aider:
    build:
      context: ./docker/aider
      dockerfile: Dockerfile
    container_name: frontier-aider
    restart: unless-stopped
    volumes:
      - ~/code:/workspace
      - ./config/aider:/root/.config/aider
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    stdin_open: true
    tty: true
    profiles:
      - development
    networks:
      - frontier-llm-network

volumes:
  ollama-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${OLLAMA_MODELS_PATH:-./data/ollama-models}

networks:
  frontier-llm-network:
    external: true