services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: frontier-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ${PROMETHEUS_CONFIG_PATH:-${PWD}/stacks/common/monitoring/config/prometheus}:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - frontier-llm-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: frontier-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ${GRAFANA_CONFIG_PATH:-${PWD}/stacks/common/monitoring/config/grafana}/provisioning:/etc/grafana/provisioning
      - ${GRAFANA_CONFIG_PATH:-${PWD}/stacks/common/monitoring/config/grafana}/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-changeme}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      - frontier-llm-network

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: frontier-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - frontier-llm-network

  # NVIDIA GPU Exporter (optional, for GPU metrics)
  nvidia-exporter:
    image: nvidia/dcgm-exporter:latest
    container_name: frontier-nvidia-exporter
    restart: unless-stopped
    ports:
      - "9400:9400"
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/nvidiactl
      - /dev/nvidia0
    profiles:
      - gpu
    networks:
      - frontier-llm-network

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  frontier-llm-network:
    external: true