# Docker Compose override for CUDA (NVIDIA GPU) support
# Usage: docker-compose -f docker-compose.yml -f docker-compose.cuda.yml up

services:
  mistral:
    # Note: deploy.resources is only supported in Docker Swarm mode
    # For standard docker-compose, use runtime and environment variables:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # Uncomment below if using Docker Swarm:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]