# Docker Compose configuration for Mistral.rs
# Common monitoring services are included via docker-compose-wrapper.sh

services:
  # Mistral.rs Inference Server
  mistral:
    build:
      context: /Users/sam/code/sandbox/frontier-llm-mac-stack/stacks/mistral/docker
      dockerfile: Dockerfile
    image: frontier-mistral:latest
    container_name: frontier-mistral
    restart: unless-stopped
    ports:
      - "${MISTRAL_API_PORT:-8080}:8080"
    volumes:
      - ./data/mistral-models:/models
      - ./config/mistral:/config
    environment:
      - RUST_LOG=${MISTRAL_LOG_LEVEL:-info}
      - MISTRAL_MODEL_PATH=/models
      - MISTRAL_PORT=${MISTRAL_API_PORT:-8080}
      - MISTRAL_HOST=0.0.0.0
      - MISTRAL_MAX_BATCH_SIZE=${MISTRAL_MAX_BATCH_SIZE:-8}
      - MISTRAL_MODEL_TYPE=${MISTRAL_MODEL_TYPE:-plain}
      - MISTRAL_MODEL_ID=${MISTRAL_MODEL_ID:-${DEFAULT_MODEL}}
      - MISTRAL_USE_V5_MODE=${MISTRAL_USE_V5_MODE:-true}
      # Metal Acceleration
      - MISTRAL_DEVICE=${MISTRAL_DEVICE:-metal}
      - MISTRAL_METAL_DEVICE_ID=${MISTRAL_METAL_DEVICE_ID:-0}
      - MISTRAL_USE_FLASH_ATTENTION=${MISTRAL_USE_FLASH_ATTENTION:-true}
      - MISTRAL_METAL_HEAP_SIZE=${MISTRAL_METAL_HEAP_SIZE:-68719476736}
      - MISTRAL_METAL_COMMAND_BUFFER_SIZE=${MISTRAL_METAL_COMMAND_BUFFER_SIZE:-1073741824}
      # Memory Management
      - MISTRAL_MAX_SEQ_LEN=${MISTRAL_MAX_SEQ_LEN:-32768}
      - MISTRAL_MEMORY_FRACTION=${MISTRAL_MEMORY_FRACTION:-0.9}
      - MISTRAL_KV_CACHE_DTYPE=${MISTRAL_KV_CACHE_DTYPE:-f16}
      - MISTRAL_ENABLE_MEMORY_POOLING=${MISTRAL_ENABLE_MEMORY_POOLING:-true}
      - MISTRAL_MEMORY_POOL_SIZE=${MISTRAL_MEMORY_POOL_SIZE:-8589934592}
      # Performance Tuning
      - MISTRAL_NUM_THREADS=${MISTRAL_NUM_THREADS:-0}
      - MISTRAL_TENSOR_PARALLEL_SIZE=${MISTRAL_TENSOR_PARALLEL_SIZE:-1}
      - MISTRAL_PIPELINE_PARALLEL_SIZE=${MISTRAL_PIPELINE_PARALLEL_SIZE:-1}
      - MISTRAL_USE_GRAPH_CAPTURE=${MISTRAL_USE_GRAPH_CAPTURE:-true}
      - MISTRAL_PREFILL_CHUNK_SIZE=${MISTRAL_PREFILL_CHUNK_SIZE:-2048}
      - MISTRAL_DECODE_CHUNK_SIZE=${MISTRAL_DECODE_CHUNK_SIZE:-256}
      # Quantization
      - MISTRAL_DEFAULT_QUANTIZATION=${MISTRAL_DEFAULT_QUANTIZATION:-q5_k_m}
      - MISTRAL_DYNAMIC_QUANTIZATION=${MISTRAL_DYNAMIC_QUANTIZATION:-true}
      - MISTRAL_QUANTIZATION_CACHE_SIZE=${MISTRAL_QUANTIZATION_CACHE_SIZE:-1073741824}
      # Inference Optimization
      - MISTRAL_ENABLE_CONTINUOUS_BATCHING=${MISTRAL_ENABLE_CONTINUOUS_BATCHING:-true}
      - MISTRAL_MAX_RUNNING_REQUESTS=${MISTRAL_MAX_RUNNING_REQUESTS:-16}
      - MISTRAL_MAX_TOTAL_TOKENS=${MISTRAL_MAX_TOTAL_TOKENS:-131072}
      - MISTRAL_ENABLE_PREFIX_CACHING=${MISTRAL_ENABLE_PREFIX_CACHING:-true}
      - MISTRAL_PREFIX_CACHE_SIZE=${MISTRAL_PREFIX_CACHE_SIZE:-2147483648}
      # Metal-specific Optimizations
      - MISTRAL_METAL_SHADER_VARIANT=${MISTRAL_METAL_SHADER_VARIANT:-optimized}
      - MISTRAL_METAL_SIMD_REDUCTION=${MISTRAL_METAL_SIMD_REDUCTION:-true}
      - MISTRAL_METAL_ASYNC_DISPATCH=${MISTRAL_METAL_ASYNC_DISPATCH:-true}
      - MISTRAL_METAL_COMMAND_QUEUE_SIZE=${MISTRAL_METAL_COMMAND_QUEUE_SIZE:-64}
    # Command is handled by docker-entrypoint.sh based on environment variables
    # To use config.toml, set MISTRAL_MODEL_TYPE=toml and mount config at /models/config.toml
    deploy:
      resources:
        limits:
          memory: ${MISTRAL_MEMORY_LIMIT:-64G}
        reservations:
          memory: ${MISTRAL_MEMORY_RESERVATION:-32G}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MISTRAL_API_PORT:-8080}/health"]
      interval: ${MISTRAL_HEALTH_INTERVAL:-30s}
      timeout: ${MISTRAL_HEALTH_TIMEOUT:-10s}
      retries: ${MISTRAL_HEALTH_RETRIES:-3}
      start_period: ${MISTRAL_HEALTH_START_PERIOD:-60s}
    networks:
      - frontier-llm-network
      - frontier-monitoring
    logging:
      driver: "json-file"
      options:
        max-size: ${MISTRAL_LOG_MAX_SIZE:-10m}
        max-file: ${MISTRAL_LOG_MAX_FILE:-3}

  # Ollama API Compatibility Proxy
  mistral-ollama-proxy:
    build:
      context: /Users/sam/code/sandbox/frontier-llm-mac-stack/stacks/mistral/api-proxy
      dockerfile: Dockerfile
    image: frontier-mistral-ollama-proxy:latest
    container_name: frontier-mistral-ollama-proxy
    restart: unless-stopped
    ports:
      - "${OLLAMA_API_PORT:-11434}:11434"
    environment:
      - RUST_LOG=${PROXY_LOG_LEVEL:-info}
      - MISTRAL_URL=http://mistral:8080
      - BIND_ADDRESS=0.0.0.0:11434
    depends_on:
      - mistral
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - frontier-llm-network
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3

networks:
  frontier-llm-network:
    external: true
  frontier-monitoring:
    name: frontier-monitoring
    external: true