version: '3.8'

services:
  # Nginx reverse proxy for security
  nginx:
    image: nginx:alpine
    container_name: frontier-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/ssl:/etc/nginx/ssl
    networks:
      - frontier-llm-network

networks:
  frontier-llm-network:
    external: true