global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['frontier-node-exporter:9100']

  - job_name: 'ollama'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontier-ollama:11434']

  - job_name: 'grafana'
    static_configs:
      - targets: ['frontier-grafana:3000']